//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargo_Firmaları
    {
        public string KargoFirmaID { get; set; }
        public string FirmaAdı { get; set; }
        public string ÜlkeID { get; set; }
    
        public virtual Ülke Ülke { get; set; }
    }
}
