//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparişler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparişler()
        {
            this.SiparişDetayları = new HashSet<SiparişDetayları>();
        }
    
        public string SiparişID { get; set; }
        public string MüşteriID { get; set; }
        public string Tarih { get; set; }
        public string ToplamFiyat { get; set; }
        public string Durum { get; set; }
    
        public virtual Müşteriler Müşteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparişDetayları> SiparişDetayları { get; set; }
    }
}
