//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ürünler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ürünler()
        {
            this.Sepet = new HashSet<Sepet>();
            this.SiparişDetayları = new HashSet<SiparişDetayları>();
            this.ÜrünMarka = new HashSet<ÜrünMarka>();
            this.ÜrünÖzellikleri = new HashSet<ÜrünÖzellikleri>();
        }
    
        public string ÜrünID { get; set; }
        public string KategoriID { get; set; }
        public string ÜrünAdı { get; set; }
        public string Fiyat { get; set; }
        public string StokMiktarı { get; set; }
        public string Açıklama { get; set; }
        public string ResimURL { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparişDetayları> SiparişDetayları { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÜrünMarka> ÜrünMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÜrünÖzellikleri> ÜrünÖzellikleri { get; set; }
    }
}
